language: java
sudo: required
jdk:
  - openjdk8
services:
  - docker
branches:
  only:
    - main
before_install:
  - 'curl -O https://download.clojure.org/install/linux-install-1.10.2.774.sh'
  - 'chmod +x linux-install-1.10.2.774.sh'
  - 'sudo ./linux-install-1.10.2.774.sh'
script:
  - 'clojure -M:test:runner'
  - 'docker build . -t sansarip/pensive-dubinsky'
